# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Mangoo"
description: "Fresh and Healthy Mangos for Everybody!"

# URL Options
baseurl: "" # Leave blank unless hosting under a subpath
url: "" # Update with your final domain

# Repo
repository: ErickSPS/my-static-website

## RPECK 09/01/2025 - Collections
## Used to output various groups of data objects
collections: 
  - products

## RPECK 09/01/2025 - Stripe Details
stripe: 
  publishable_key: pk_test_67kzaipYLaDOd1vueE00Q4ai

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

# Includes
# Allows us to include the various other blocks of content we may use on the site
include:
  - _pages

# Exclude
# Exclude these files from the build.
exclude:
  - .github
  - .editorconfig
  - .gitignore
  - _config.yml
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - config.ru
  - CONTRIBUTING.md
  - LICENSE
  - Procfile
  - Rakefile
  - README.md
  - static.json
  
# Github
github:
  is_project_page: false